language: node_js
node_js:
- "stable"

install:
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - npm run lint

notifications:
  slack: project-unic0rn:WZpu8mIAHP8zy2a4NqfMTFuq