version: '3'

services:
  db:
    build: ./db/
    env_file:
      - .env
    ports:
      - $DB_HOST_PORT:$DB_PORT
    volumes:
      - db_volume:/var/lib/postgresql/data
    command: postgres -p $DB_PORT

  api:
    build: .
    env_file:
      - .env
    ports:
     - "8080:8080"
    volumes:
      - ./server:/app/server
    command: dockerize -wait tcp://db:$DB_PORT -- npm start
    depends_on:
      - db

volumes:
  db_volume:
