version: '3'

services:
  db:
    build: ./db/
    env_file:
      - .env
    ports:
      - $DB_HOST_PORT:$DB_PORT
    volumes:
      - db_volume:/var/lib/postgresql/data
    command: postgres -p $DB_PORT

volumes:
  db_volume:
